export {
  api,
  catalogosService,
  deportistasService,
  historiaClinicaService,
  respuestaGruposService,
  formularioRespuestasService,
  citasService,
  archivosService,
  formulariosService,
  plantillasService,
  documentosService,
  healthCheck,
  // Tipos
  type ApiResponse,
  type PaginatedResponse,
  type Catalogo,
  type CatalogoItem,
  type Deportista,
  type Formulario,
  type FormularioCampo,
  type HistoriaClinica,
  type Cita,
  type RespuestaGrupo,
  type FormularioRespuesta,
  type ArchivoCinico,
  type PlantillaClinica,
} from './apiClient';